package com.jg.bookstore.domain.exception;

public enum ErrorCode {

    AUTHOR_NOT_FOUND,
    BOOK_NOT_FOUND,
    ORDER_EMPTY,
    ORDER_ENTRY_QUANTITY_ERROR,
    ORDER_NOT_FOUND,
    ORDER_INVALID_STATUS,
    ORDER_IS_FINALISED,
    ORDER_NOT_ENOUGH_STOCK,
    CURRENCY_NOT_FOUND,
    ACCOUNT_NOT_FOUND,
    CLIENT_NOT_FOUND,
    INVALID_JWT_TOKEN

}
